#!/bin/sh

WITH_SYSTEMD=0

__configure() {
    echo "Configure bloonix with systemd=$WITH_SYSTEMD"

    if [ $WITH_SYSTEMD -eq 1 ] ; then
        systemctl preset bloonix-agent.service
    else
        if test ! -e "/etc/default/bloonix-agent" ; then
            echo 'LOGGER="/usr/bin/logger -t bloonix-agent"' >/etc/default/bloonix-agent
        fi
        update-rc.d bloonix-agent defaults >/dev/null
    fi
}

case "$1" in
    configure) __configure ;;
esac

/usr/bin/bloonix-init-agent

echo "Starting (condrestart) bloonix-agent..";

if [ $WITH_SYSTEMD -eq 1 ] ; then
    systemctl condrestart bloonix-agent.service
else
    /etc/init.d/bloonix-agent condrestart
fi

exit 0
