#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
    echo "Removing bloonix-agent.."

    if [ -e "/lib/systemd" ] ; then
        systemctl --no-reload disable bloonix-agent.service
        echo "Stopping bloonix-agent.."
        systemctl stop bloonix-agent.service
        systemctl daemon-reload
    else
        update-rc.d -f bloonix-agent remove >/dev/null
        echo "Stopping bloonix-agent.."
        if [ -e "/usr/share/upstart" ] ; then
            service bloonix-agent stop
        else
            /etc/init.d/bloonix-agent stop
        fi
    fi
fi

exit 0
