#!/bin/sh

set -e

WITH_SYSTEMD=0

__configure() {
    echo "Configure bloonix with systemd=$WITH_SYSTEMD"

    if [ $WITH_SYSTEMD -eq 1 ] ; then
        systemctl preset bloonix-agent.service
    else
        if test ! -e "/etc/default/bloonix-agent" ; then
            echo 'LOGGER="/usr/bin/logger -t bloonix-agent"' >/etc/default/bloonix-agent
        fi
        update-rc.d bloonix-agent defaults >/dev/null
    fi
}

case "$1" in
    configure) __configure ;;
esac



if [ ! -e "/etc/bloonix/agent/main.conf" ] ; then
    mkdir -p /etc/bloonix/agent
    chown root:root /etc/bloonix /etc/bloonix/agent
    chmod 755 /etc/bloonix /etc/bloonix/agent
    cp -a /usr/lib/bloonix/etc/agent/main.conf /etc/bloonix/agent/main.conf
    chown root:bloonix /etc/bloonix/agent/conf.d /etc/bloonix/agent/main.conf
    chmod 640 /etc/bloonix/agent/main.conf
fi
if [ ! -e "/etc/bloonix/agent/conf.d" ] ; then
    mkdir -p /etc/bloonix/agent/conf.d
    chown root:bloonix /etc/bloonix/agent/conf.d
    chmod 750 /etc/bloonix/agent/conf.d
fi
if [ ! -e "/etc/bloonix/agent/sudoers.d" ] ; then
    mkdir -p /etc/bloonix/agent/sudoers.d
    chown root:root /etc/bloonix/agent/sudoers.d
    chmod 755 /etc/bloonix/agent/sudoers.d
fi

# fix permissions
chown root:root /etc/bloonix /etc/bloonix/agent /etc/bloonix/agent/sudoers.d
chmod 755 /etc/bloonix /etc/bloonix/agent /etc/bloonix/agent/sudoers.d
chown root:bloonix /etc/bloonix/agent/*.conf
chown root:bloonix /etc/bloonix/agent/conf.d
chown root:bloonix /etc/bloonix/agent/conf.d/*.conf
chown root:root /etc/bloonix/agent/sudoers.d/*
chmod 440 /etc/bloonix/agent/sudoers.d/*
chmod 750 /etc/bloonix/agent/conf.d
chmod -R g-w /etc/bloonix

echo "Starting (condrestart) bloonix-agent..";

if [ $WITH_SYSTEMD -eq 1 ] ; then
    systemctl condrestart bloonix-agent.service
else
    /etc/init.d/bloonix-agent condrestart
fi

exit 0
